#!/bin/sh

. /lib/recovery-mode/l10n.sh

if [ "$1" = "test" ]; then
  echo $(eval_gettext "Enable networking")
  exit 0
fi

# Check for existing connectivity
check_connectivity() {
    ip route get 1.2.3.4 >/dev/null 2>&1
    retval_route=$?

    grep ^nameserver -q /etc/resolv.conf
    retval_resolve=$?

    if [ "$retval_route" = "0" ] && [ "$retval_resolve" ]; then
        exit 0
    fi
}

# Start by trying to bring everything up
ifup -a
check_connectivity

# Then look for Network Manager
if [ -f /etc/init/network-manager.conf ]; then
    start dbus
    start network-manager
    check_connectivity
fi

# Try running dhclient on everything else
cd /sys/class/net/
for interface in *; do
    dhclient -1 $interface
    check_connectivity
done

exit 0
